import { lazy, ReactNode } from 'react';

// Lazy load all tools
const toolComponents: Record<string, React.LazyExoticComponent<() => ReactNode>> = {
  // Productivity & Planning Tools
  'advanced-todo-list': lazy(() => import('./AdvancedTodoList')),
  'pomodoro-timer': lazy(() => import('./PomodoroTimer')),
  'countdown-timer': lazy(() => import('./CountdownTimer')),
  'stopwatch': lazy(() => import('./Stopwatch')),
  'world-clock': lazy(() => import('./WorldClock')),
  'meeting-scheduler': lazy(() => import('./MeetingScheduler')),
  'habit-tracker': lazy(() => import('./HabitTracker')),
  'daily-journal': lazy(() => import('./DailyJournal')),
  'goal-tracker': lazy(() => import('./GoalTracker')),
  'focus-music-player': lazy(() => import('./FocusMusicPlayer')),
  'distraction-blocker': lazy(() => import('./DistractionBlocker')),
  'water-reminder': lazy(() => import('./WaterReminder')),
  'posture-reminder': lazy(() => import('./PostureReminder')),
  'eye-break-reminder': lazy(() => import('./EyeBreakReminder')),
  'random-task-picker': lazy(() => import('./RandomTaskPicker')),
  'priority-matrix': lazy(() => import('./PriorityMatrix')),
  'kanban-board': lazy(() => import('./KanbanBoard')),
  'mind-map-creator': lazy(() => import('./MindMapCreator')),
  'cornell-notes': lazy(() => import('./CornellNotes')),
  'daily-planner': lazy(() => import('./DailyPlanner')),
  'weekly-planner': lazy(() => import('./WeeklyPlanner')),
  'monthly-calendar': lazy(() => import('./MonthlyCalendar')),
  'time-blocking': lazy(() => import('./TimeBlocking')),
  'focus-stats': lazy(() => import('./FocusStats')),
  'stretch-reminders': lazy(() => import('./StretchReminders')),
  'gratitude-journal': lazy(() => import('./GratitudeJournal')),
  'mood-tracker': lazy(() => import('./MoodTracker')),
  'energy-tracker': lazy(() => import('./EnergyTracker')),
  'screen-time-tracker': lazy(() => import('./ScreenTimeTracker')),
  'decision-matrix': lazy(() => import('./DecisionMatrix')),
  'pareto-analyzer': lazy(() => import('./ParetoAnalyzer')),
  'wheel-of-life': lazy(() => import('./WheelOfLife')),
  'swot-analysis': lazy(() => import('./SwotAnalysis')),
  'okr-tracker': lazy(() => import('./OkrTracker')),
  'personal-kpi': lazy(() => import('./PersonalKpi')),
  'reading-list': lazy(() => import('./ReadingList')),
  'book-summary': lazy(() => import('./BookSummary')),
  'spaced-repetition': lazy(() => import('./SpacedRepetition')),
  'pomodoro-history': lazy(() => import('./PomodoroHistory')),
  'reflection-prompts': lazy(() => import('./ReflectionPrompts')),

  // Finance & Calculators Tools
  'compound-interest': lazy(() => import('./CompoundInterest')),
  'retirement': lazy(() => import('./Retirement')),
  'savings-goal': lazy(() => import('./SavingsGoal')),
  'net-worth': lazy(() => import('./NetWorth')),
  'expense-splitter': lazy(() => import('./ExpenseSplitter')),
  'bill-splitter': lazy(() => import('./BillSplitter')),
  'salary-calculator': lazy(() => import('./SalaryCalculator')),
  'freelance-rate': lazy(() => import('./FreelanceRate')),
  'roi': lazy(() => import('./ROI')),
  'break-even': lazy(() => import('./BreakEven')),
  'profit-margin': lazy(() => import('./ProfitMargin')),
  'markup': lazy(() => import('./Markup')),
  'discount': lazy(() => import('./Discount')),
  'sales-tax': lazy(() => import('./SalesTax')),
  'vat': lazy(() => import('./VAT')),
  'crypto-profit': lazy(() => import('./CryptoProfit')),
  'stock-tracker': lazy(() => import('./StockTracker')),
  'mortgage': lazy(() => import('./Mortgage')),
  'car-loan': lazy(() => import('./CarLoan')),
  'credit-card-payoff': lazy(() => import('./CreditCardPayoff')),
  'debt-snowball': lazy(() => import('./DebtSnowball')),
  'emergency-fund': lazy(() => import('./EmergencyFund')),
  'fire-calculator': lazy(() => import('./FIRECalculator')),
  '50-30-20-budget': lazy(() => import('./Budget503020')),
  'zero-based-budget': lazy(() => import('./ZeroBasedBudget')),
  'envelope-budget': lazy(() => import('./EnvelopeBudget')),
  'paycheck-planner': lazy(() => import('./PaycheckPlanner')),
  'side-hustle-profit': lazy(() => import('./SideHustleProfit')),
  'rental-roi': lazy(() => import('./RentalROI')),
  'house-affordability': lazy(() => import('./HouseAffordability')),
  'refinance': lazy(() => import('./Refinance')),
  'inflation': lazy(() => import('./Inflation')),
  'gold-price': lazy(() => import('./GoldPrice')),
  'fuel-cost': lazy(() => import('./FuelCost')),
  'mileage-reimbursement': lazy(() => import('./MileageReimbursement')),
  'overtime-pay': lazy(() => import('./OvertimePay')),
  'take-home-pay': lazy(() => import('./TakeHomePay')),
  'cost-of-living': lazy(() => import('./CostOfLiving')),

  // Text & Code Tools
  'qr-code-generator': lazy(() => import('./QrCodeGenerator')),
  'barcode-generator': lazy(() => import('./BarcodeGenerator')),
  'password-generator': lazy(() => import('./PasswordGenerator')),
  'json-formatter': lazy(() => import('./JsonFormatter')),
  'sql-formatter': lazy(() => import('./SqlFormatter')),
  'css-formatter': lazy(() => import('./CssFormatter')),
  'html-formatter': lazy(() => import('./HtmlFormatter')),
  'javascript-formatter': lazy(() => import('./JavaScriptFormatter')),
  'python-formatter': lazy(() => import('./PythonFormatter')),
  'base64-encode-decode': lazy(() => import('./Base64EncodeDecode')),
  'url-encode-decode': lazy(() => import('./UrlEncodeDecode')),
  'word-counter': lazy(() => import('./WordCounter')),
  'case-converter': lazy(() => import('./CaseConverter')),
  'text-reverser': lazy(() => import('./TextReverser')),
  'escape-unescape': lazy(() => import('./EscapeUnescape')),
  'lorem-ipsum-generator': lazy(() => import('./LoremIpsumGenerator')),
  'color-palette': lazy(() => import('./ColorPalette')),
  'gradient-generator': lazy(() => import('./GradientGenerator')),
  'uuid-generator': lazy(() => import('./UuidGenerator')),
  'hash-generator': lazy(() => import('./HashGenerator')),
  'hash-generator-text': lazy(() => import('./HashGenerator')),
  'regex-tester': lazy(() => import('./RegexTester')),
  'tip-calculator': lazy(() => import('./TipCalculator')),
  'currency-converter': lazy(() => import('./CurrencyConverter')),
  'text-diff': lazy(() => import('./TextDiff')),
  'jwt-decoder': lazy(() => import('./JwtDecoder')),

  // Image & Design Tools
  'image-compressor': lazy(() => import('./ImageCompressor')),
  'image-resizer': lazy(() => import('./ImageResizer')),
  'image-cropper': lazy(() => import('./ImageCropper')),
  'image-converter': lazy(() => import('./ImageConverter')),
  'jpg-to-png': lazy(() => import('./JpgToPng')),
  'png-to-jpg': lazy(() => import('./PngToJpg')),
  'webp-converter': lazy(() => import('./WebpConverter')),
  'svg-to-png': lazy(() => import('./SvgToPng')),
  'png-to-ico': lazy(() => import('./PngToIco')),
  'remove-background': lazy(() => import('./RemoveBg')),
  'exif-viewer': lazy(() => import('./ExifViewer')),
  'add-text-to-image': lazy(() => import('./AddTextToImage')),
  'image-to-base64': lazy(() => import('./ImageToBase64')),
  'base64-to-image': lazy(() => import('./Base64ToImage')),
  'favicon-generator': lazy(() => import('./FaviconGenerator')),
  'color-picker': lazy(() => import('./ColorPicker')),

  // File Converters & Editors (single-purpose tools)
  'json-to-csv': lazy(() => import('./JsonToCsv')),
  'csv-to-json': lazy(() => import('./CsvToJson')),
  'csv-editor': lazy(() => import('./CsvEditor')),
  'markdown-to-html': lazy(() => import('./MarkdownToHtml')),
  'html-to-markdown': lazy(() => import('./HtmlToMarkdown')),
  'html-entity': lazy(() => import('./HtmlEntity')),
  'json-to-yaml': lazy(() => import('./JsonToYaml')),
  'yaml-to-json': lazy(() => import('./YamlToJson')),
  'xml-to-json': lazy(() => import('./XmlToJson')),
  'json-to-xml': lazy(() => import('./JsonToXml')),
  'xml-formatter': lazy(() => import('./XmlFormatter')),
  'toml-to-json': lazy(() => import('./TomlToJson')),
  'json-to-toml': lazy(() => import('./JsonToToml')),
  'json-to-excel': lazy(() => import('./JsonToExcel')),
  'excel-to-json': lazy(() => import('./ExcelToJson')),

  // Generators & Makers
  'color-blind-simulator': lazy(() => import('./ColorBlindSimulator')),
  'box-shadow': lazy(() => import('./BoxShadowGenerator')),
  'text-shadow': lazy(() => import('./TextShadowGenerator')),
  'border-radius': lazy(() => import('./BorderRadiusGenerator')),
  'css-cursor': lazy(() => import('./CssCursorGenerator')),
  'button-generator': lazy(() => import('./ButtonGenerator')),
  'glassmorphism': lazy(() => import('./GlassmorphismGenerator')),
  'neumorphism': lazy(() => import('./NeumorphismGenerator')),

  // Web & SEO Tools
  'flexbox-playground': lazy(() => import('./FlexboxPlayground')),
  'grid-playground': lazy(() => import('./GridPlayground')),
  'responsive-tester': lazy(() => import('./ResponsiveTester')),
  'opengraph-generator': lazy(() => import('./OpenGraphGenerator')),
  'meta-tag-generator': lazy(() => import('./MetaTagGenerator')),
  'robots-txt': lazy(() => import('./RobotsTxtGenerator')),
  'sitemap-xml': lazy(() => import('./SitemapGenerator')),
  'password-strength': lazy(() => import('./PasswordStrength')),
  'regex-tester-seo': lazy(() => import('./RegexTester')), // Alias

  // Time & Utilities
  'html-entities': lazy(() => import('./HtmlEntity')), // Alias
  'ascii-art': lazy(() => import('./AsciiArtGenerator')),
  'emoji-picker': lazy(() => import('./EmojiPicker')),
  'tally-counter': lazy(() => import('./TallyCounter')),
  'invoice-generator': lazy(() => import('./InvoiceGenerator')),
  'world-clock-pro': lazy(() => import('./WorldClockPro')),

  // PDF-specific tools
  'pdf-to-text': lazy(() => import('./PdfToText')),
  'pdf-tools': lazy(() => import('./PdfTools')),
  'merge-pdfs': lazy(() => import('./MergePdfs')),
  'split-pdf': lazy(() => import('./SplitPdf')),
  'images-to-pdf': lazy(() => import('./ImagesToPdf')),
  'pdf-to-images': lazy(() => import('./PdfToImages')),
  'rotate-pdf': lazy(() => import('./RotatePdf')),
  'compress-pdf': lazy(() => import('./CompressPdf')),
  'watermark-pdf': lazy(() => import('./WatermarkPdf')),
  'add-pdf-password': lazy(() => import('./AddPdfPassword')),
  'remove-pdf-password': lazy(() => import('./RemovePdfPassword')),
  'text-to-pdf': lazy(() => import('./TextToPdf')),
  'markdown-to-pdf': lazy(() => import('./MarkdownToPdf')),
  'rtf-to-pdf': lazy(() => import('./RtfToPdf')),
  'epub-to-pdf': lazy(() => import('./EpubToPdf')),
  'odt-to-pdf': lazy(() => import('./OdtToPdf')),
  'pdf-to-epub': lazy(() => import('./PdfToEpub')),
  'word-to-pdf': lazy(() => import('./WordToPdf')),
  'excel-to-pdf': lazy(() => import('./ExcelToPdf')),
  'ppt-to-pdf': lazy(() => import('./PptToPdf')),
  'html-to-pdf': lazy(() => import('./HtmlToPdf')),

  // Office & Document Converters
  'office-tools': lazy(() => import('./OfficeTools')),

  // Archive & File Tools
  'zip-creator': lazy(() => import('./ZipCreator')),
  'zip-extractor': lazy(() => import('./ZipExtractor')),
  'tar-extractor': lazy(() => import('./TarExtractor')),
  '7z-extractor': lazy(() => import('./SevenZipExtractor')),
  'rar-extractor': lazy(() => import('./RarExtractor')),
  'file-merger': lazy(() => import('./FileMerger')),
  'file-splitter': lazy(() => import('./FileSplitter')),
  'file-comparator': lazy(() => import('./FileComparator')),
  'duplicate-finder': lazy(() => import('./DuplicateFinder')),
  'file-validator': lazy(() => import('./FileValidator')),
  'bulk-renamer': lazy(() => import('./BulkRenamer')),
  'file-type-detector': lazy(() => import('./FileTypeDetector')),
  // hash-generator is already in Text & Code Tools

  // Media Tools
  'video-to-gif': lazy(() => import('./VideoToGif')),
  'audio-converter': lazy(() => import('./AudioConverter')),
  'gif-maker': lazy(() => import('./GifMaker')),

  // Health & Fitness Tools
  'bmi-bmr-tdee': lazy(() => import('./BmiBmrTdee')),
  'body-fat-percent': lazy(() => import('./BodyFatPercent')),
  'one-rep-max': lazy(() => import('./OneRepMax')),
  'macro-calculator': lazy(() => import('./MacroCalculator')),
  'calorie-deficit': lazy(() => import('./CalorieDeficit')),
  'water-intake': lazy(() => import('./WaterIntake')),
  'sleep-calculator': lazy(() => import('./SleepCalculator')),
  'heart-rate-zones': lazy(() => import('./HeartRateZones')),
  'vo2-max': lazy(() => import('./VO2Max')),
  'pregnancy-due-date': lazy(() => import('./PregnancyDueDate')),
  'ovulation-calendar': lazy(() => import('./OvulationCalendar')),
  'period-tracker': lazy(() => import('./PeriodTracker')),
  'baby-name-generator': lazy(() => import('./BabyNameGenerator')),
  'height-predictor': lazy(() => import('./HeightPredictor')),
  'ideal-weight': lazy(() => import('./IdealWeight')),
  'waist-to-hip': lazy(() => import('./WaistToHip')),
  'steps-tracker': lazy(() => import('./StepsTracker')),
  'workout-log': lazy(() => import('./WorkoutLog')),
  'running-pace': lazy(() => import('./RunningPace')),
  'marathon-predictor': lazy(() => import('./MarathonPredictor')),
  'cycling-power': lazy(() => import('./CyclingPower')),
  'yoga-sequence': lazy(() => import('./YogaSequence')),
  'meditation-timer': lazy(() => import('./MeditationTimer')),
  'breathing-exercises': lazy(() => import('./BreathingExercises')),
  'mental-health-quiz': lazy(() => import('./MentalHealthQuiz')),
  'anxiety-test': lazy(() => import('./AnxietyTest')),
  'burnout-quiz': lazy(() => import('./BurnoutQuiz')),
  'nutrition-lookup': lazy(() => import('./NutritionLookup')),
  'recipe-calories': lazy(() => import('./RecipeCalories')),
  'fasting-timer': lazy(() => import('./FastingTimer')),

  // Fun & Entertainment
  'yes-no-wheel': lazy(() => import('./YesNoWheel')),
  'random-number-wheel': lazy(() => import('./RandomNumberWheel')),
  'coin-flipper': lazy(() => import('./CoinFlipper')),
  'dice-roller': lazy(() => import('./DiceRoller')),
  'wheel-of-names': lazy(() => import('./WheelOfNames')),
  'name-picker': lazy(() => import('./RandomTaskPicker')),
  'truth-or-dare': lazy(() => import('./TruthOrDare')),
  'would-you-rather': lazy(() => import('./WouldYouRather')),
  'this-or-that': lazy(() => import('./ThisOrThat')),
  'magic-8-ball': lazy(() => import('./Magic8Ball')),
  'love-calculator': lazy(() => import('./LoveCalculator')),
  'personality-quiz': lazy(() => import('./PersonalityQuiz')),
  'random-country': lazy(() => import('./RandomCountry')),
  'movie-picker': lazy(() => import('./MoviePicker')),
  'password-wheel': lazy(() => import('./PasswordWheel')),
  'mood-picker': lazy(() => import('./MoodTracker')),
  'excuse-generator': lazy(() => import('./ExcuseGenerator')),
  'roast-generator': lazy(() => import('./RoastGenerator')),
  'tarot-reader': lazy(() => import('./TarotReader')),

  // Social Media Mockups
  'fake-tweet': lazy(() => import('./FakeTweet')),
  'fake-instagram': lazy(() => import('./FakeInstagram')),
  'fake-youtube': lazy(() => import('./FakeYoutube')),
  'meme-caption': lazy(() => import('./MemeCaption')),
  'emoji-story': lazy(() => import('./EmojiStory')),

  // Interactive Tests & Misc
  'typing-test': lazy(() => import('./TypingTest')),
  'reaction-time': lazy(() => import('./ReactionTime')),
  'color-blindness': lazy(() => import('./ColorBlindness')),
  'hearing-test': lazy(() => import('./HearingTest')),
  'age-in-seconds': lazy(() => import('./AgeInSeconds')),
  'days-until': lazy(() => import('./DaysUntil')),
};

// Default skeleton component for tools not yet implemented
const SkeletonTool = () => (
  <div className="space-y-4">
    <div className="text-center py-12">
      <div className="text-6xl mb-4">🚧</div>
      <h3 className="text-xl font-semibold text-slate-900 dark:text-slate-100 mb-2">
        Coming Soon
      </h3>
      <p className="text-slate-600 dark:text-slate-400">
        This tool is under development. Check back soon!
      </p>
    </div>
  </div>
);

export const getToolComponent = (slug: string) => {
  const Component = toolComponents[slug];
  return Component || (() => <SkeletonTool />);
};
